# Generated by Django 3.0.6 on 2020-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('ordername', models.CharField(max_length=255)),
            ],
        ),
    ]
